### ISSUE TITLE
Doesn't work without CommonJS

### ISSUE THREAD

**Issue by ivw** [primus/eventemitter3#22]
When you only want to include the index.js in your html, to use it without node/browserify, it will give an error because `module` is not defined.

The way other libraries (like eventemitter2) handle this is checking if module or exports exist:
http://stackoverflow.com/questions/12571737/module-exports-client-side
http://www.matteoagosti.com/blog/2013/02/24/writing-javascript-modules-for-both-browser-and-node/

**Comment by 3rd-Eden** [comment]
We already support bowser, component and node to install the module. I don't really see a need to adapt to code any further. There are already enough tools and build processes to just work with this pattern.

What we could do is add an extra dist file which just runs `browserify index.js --standalone EventEmitter` but you can just as easily run it your self.

**Comment by ivw** [comment]
Bower is supported, but broken, as described in this issue. I should have made clear this was not a new feature request.

With Bower (or any other method other than CommonJS) you download the library and reference the .js in your html.
This will currently not work, because the code only works with CommonJS modules, while it's only a few lines of code to add support for a browser global (like in the links I added). You don't need an extra file.

**Comment by 3rd-Eden** [comment]
Sure, but I don't want to pollute my files with pointless code that I'm not and most of the people are not using. All these patterns add pointless bloat that why i've adapted one pattern that can be compiled reasonably easy in to different formats.

**Comment by ivw** [comment]
It's not pointless. Anyone who uses this with Bower or manual file download will need this.
That's why it's standard for almost all js libraries.

Calling it bloat doesn't seem reasonable to me too, it's a single if-else statement. That's why an extra dist file is overkill.

**Comment by 3rd-Eden** [comment]
Not gonna happen.

**Comment by Asarew** [comment]
I agree with @ivw... it's seems kind of arrogant to just say ```Not gonna happen```.
He makes a valid point and it doesn't brake the current implementation, it just adds usability!

In the words of the great philosopher Jim Jefferies ```Try not to be a cunt```, it will help you when you try to put out open source packages.

**Comment by 3rd-Eden** [comment]
As author of this module, there is nothing wrong with saying that something is not going to happen in a module because in my opinion it doesn't add any extra value to the module it self, it's my opinion and any I have every right to voice this opinion. Every line that is added to this project and is not executed by the general use case in which this module written in is simply bloat. It doesn't matter if it's a function call or an if statement, it's bloat and doesn't belong here. Especially if you consider that this use case can easily be resolved by the developer it self.

```js
var module = { exports: {} };
// load eventemitter, problem solved without having to modify the code.
```

Also, to make this perfectly clear, just because something is open source, it doesn't mean that I have to accept every single pull request. When you add new features to a project it's always best to discuss this with the author before you start writing code. It's released under the open source license. Don't like ? Fork it. That's why these buttons exist. And that's also the last thing I'm going to say about this matter.
