### ISSUE TITLE
is there a .min version available?

### ISSUE THREAD

**Issue by goldenratio** [primus/eventemitter3#38]

**Comment by 3rd-Eden** [comment]
Nope. I see no need for it either. Minification should be done on your complete application bundle, not the individual library files so the minifiers can easily remove dead code and minimize code more efficiently.

**Comment by goldenratio** [comment]
I think it doesn't hurt to have ready to go .min version.
What if, I don't have to deal with build system.

**Comment by 3rd-Eden** [comment]
I would assume that you want to minify the code for performance reasons. And without a build system you can't really bundle it, so that would mean that your application would require a minimal of 2 HTTP requests. 1 for your application code and 1 for this library. It would be a faster to bundle the app code and library in 1 file, unminified than it would be to load the library minified and your application code minified. So that doesn't make any sense in time performance gain or time invested.

But if you're feeling strongly about it, i'll be more than happy to accept a pull request which adds and generates a minified build when we publish a new release.
