### ISSUE TITLE
custom context at Emit time, rather than at On listener attach

### ISSUE THREAD

**Issue by riiiiizzzzzohmmmmm** [primus/eventemitter3#44]
Perhaps I'm just doing something wrong, but in my current usage of EE3 (which is awesome, by the way!), whenever I try to invoke `.emit()` with a custom context by using `Foo.emit.call(someContext, arg1, arg2, ...)`, I get some unexpected behavior in my event handlers.

Any guidance/feedback appreciated.

**Comment by 3rd-Eden** [comment]
You can't really do that because with `EE3Instance.emit.call(context)` is causing our `emit` to be called with `context` and not the event handlers that you assigned. 

So you could write a wrapper function for your assigned events so it calls a supplied function with a given context which can be passed in first argument or just pass the context as event argument.. 

```js
function proxy(fn) {
  return function emitter() {
    var args = Array.prototype.slice.call(arguments);
    var context = args.shift();

    fn.apply(context, args);
  }
}

ee.on('eventname', proxy(function (one, two) {
  console.log(one, two); // outputs foo, bar
  console.log(this); // outputs 'hello'
}))

ee.emit('eventname', 'hello', 'foo', 'bar')
```

**Comment by riiiiizzzzzohmmmmm** [comment]
@3rd-Eden Outstanding, thank you!
