### ISSUE TITLE
(node:6956)  issue

### ISSUE THREAD

**Issue by crazyhuggins** [primus/eventemitter3#73]
Hi, @pyrotechnick , @lpinca 

I tried to use this module as a drop-in replacement for the native one and ended up with this error message:

```js
(node:6956) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
```

With the native solution this error is gone. I am now using NodejS 7

**Comment by lpinca** [comment]
That warning comes from Node.js `EventEmitter`. `eventemitter3` does not impose any limits.

**Comment by pyrotechnick** [comment]
I'm not sure why I've been mentioned by @crazyhuggins but in the interest of closure here goes...

Provided `eventemitter3` isn't monkey-patched or otherwise augmented, the library will not throw the kinds of `MaxListenersExceededWarning` produced by [node's own `EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter).

The only reference `eventemitter3` makes to the concept of a maximum number of listeners is the [instance method `setMaxListeners` which was introduced in `f7398649013659105f95445ed6f22b6e842d7e73`](https://github.com/primus/eventemitter3/commit/f7398649013659105f95445ed6f22b6e842d7e73#diff-168726dbe96b3ce427e7fedce31bb0bcR165) to facilitate the use of [`util.inherits`](https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor).

Upon inspection, one realises the method is merely `return this` -- essentially rendering it a no-op whilst maintaining the chainable interface.

@crazyhuggins [The check for a large amount of listeners](https://github.com/nodejs/node/blob/7f909c3b7922a3c7cdca03527dd6dc3687ae4e8b/lib/events.js#L267) within node's own [`EventEmitter::addListener`](https://nodejs.org/api/events.html#events_emitter_addlistener_eventname_listener) is the most-likely source of your error.

Without knowing more information, one may only make the informed guess that `eventemitter3` is being augmented or circumvented subsequent to being included.

**Comment by lpinca** [comment]
Closing this, please comment back if needed.
